#!/usr/bin/env python3
"""
Generate a consolidated HTML report for a single security assessment directory.

Usage:
    python3 full_assessment_html.py <assessment_dir> <output_html>
"""

import csv
import html
import os
import sys
from pathlib import Path


def read_summary_csv(path):
    if not os.path.exists(path):
        return {}

    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    return rows[0] if rows else {}


def build_table(title, data):
    if not data:
        return f"<h2>{html.escape(title)}</h2><p>No data available.</p>"

    rows = []
    for key, value in data.items():
        rows.append(
            f"<tr><th>{html.escape(str(key))}</th>"
            f"<td>{html.escape(str(value))}</td></tr>"
        )

    return (
        f"<h2>{html.escape(title)}</h2>"
        "<table>"
        + "".join(rows)
        + "</table>"
    )


def find_artifacts(assessment_dir):
    patterns = [
        "*.xlsx",
        "*-vulnerability-report.html",
        "*-compliance-report.html",
        "*.zip",
        "*.json",
        "*.csv",
    ]

    files = []
    p = Path(assessment_dir)

    for pattern in patterns:
        files.extend(sorted(p.glob(pattern)))

    # Remove duplicates while preserving order
    seen = set()
    unique = []
    for file in files:
        if file.name not in seen:
            seen.add(file.name)
            unique.append(file)

    return unique


def build_artifacts_section(artifacts):
    if not artifacts:
        return "<h2>Artifacts</h2><p>No artifacts found.</p>"

    rows = []
    for artifact in artifacts:
        rows.append(
            f'<li><a href="{html.escape(artifact.name)}">'
            f"{html.escape(artifact.name)}</a></li>"
        )

    return "<h2>Artifacts</h2><ul>" + "".join(rows) + "</ul>"


def main():
    if len(sys.argv) != 3:
        print(
            "Usage: full_assessment_html.py <assessment_dir> <output_html>",
            file=sys.stderr,
        )
        sys.exit(1)

    assessment_dir = sys.argv[1]
    output_html = sys.argv[2]

    assessment_name = os.path.basename(assessment_dir)

    image_name = assessment_name
    if image_name.endswith("-security-assessment"):
        image_name = image_name[:-len("-security-assessment")]

    vuln_summary = read_summary_csv(
        os.path.join(
            assessment_dir,
            f"{image_name}-vulnerability-summary.csv",
        )
    )

    compliance_summary = read_summary_csv(
        os.path.join(
            assessment_dir,
            f"{image_name}-compliance-summary.csv",
        )
    )

    artifacts = find_artifacts(assessment_dir)

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{html.escape(assessment_name)}</title>
<style>
body {{
    font-family: Arial, sans-serif;
    margin: 40px;
    background: #f7f9fc;
    color: #222;
}}
h1 {{
    color: #1f4e79;
    border-bottom: 3px solid #1f4e79;
    padding-bottom: 10px;
}}
h2 {{
    color: #2f75b5;
    margin-top: 30px;
}}
table {{
    border-collapse: collapse;
    width: 100%;
    background: #fff;
}}
th, td {{
    border: 1px solid #d0d7de;
    padding: 8px 12px;
    text-align: left;
}}
th {{
    background: #eef4fb;
    width: 35%;
}}
ul {{
    background: #fff;
    padding: 20px 40px;
    border: 1px solid #d0d7de;
}}
a {{
    color: #1f4e79;
    text-decoration: none;
}}
a:hover {{
    text-decoration: underline;
}}
.footer {{
    margin-top: 40px;
    color: #666;
    font-size: 0.9em;
}}
</style>
</head>
<body>
<h1>{html.escape(assessment_name)}</h1>

{build_table("Vulnerability Summary", vuln_summary)}

{build_table("Compliance Summary", compliance_summary)}

{build_artifacts_section(artifacts)}

<div class="footer">
Generated by HardenX
</div>
</body>
</html>
"""

    with open(output_html, "w", encoding="utf-8") as f:
        f.write(html_content)

    print(output_html)


if __name__ == "__main__":
    main()